version: '2'
services:
    nginx:
        image: nginx:stable
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - phpfpm
        ports:
            - "8080:80"
        depends_on:
            - phpfpm
    phpfpm:
        build:
            context: ./docker
            dockerfile: Dockerfile.fpm
        env_file: ./docker/.env
        ports:
            - "9000:9000"
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql
    mysql:
        image: mysql:5.5
        env_file: ./docker/.env